name: lcms2struct_experiments
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.9
  - conda-forge::pandas==1.2.4
  - conda-forge::numpy==1.20.2
  - conda-forge::rdkit==2021.03.1
  - conda-forge::scikit-learn==0.24.2
  - conda-forge::joblib==1.0.1
  - conda-forge::more-itertools=8.7
  - conda-forge::tqdm
  - conda-forge::scipy==1.6.2
  - conda-forge::cvxpy==1.1.15
  - conda-forge::networkx==2.6.3
  - conda-forge::matplotlib=3.4
  - conda-forge::seaborn=0.11
  - bioconda::matchms==0.9.2
  - conda-forge::ipython
  - conda-forge::jupyterlab
  - conda-forge::ipykernel
