name: lcms2struct_manuscript_figures
channels:
  - conda-forge
  - default
dependencies:
  - conda-forge::python>=3.8|<3.10
  - conda-forge::pandas==1.2.4
  - conda-forge::numpy==1.20.2
  - conda-forge::scipy==1.6.2
  - conda-forge::more-itertools
  - conda-forge::tqdm
  - conda-forge::matplotlib=3.4
  - conda-forge::seaborn=0.11
  - conda-forge::ipython
  - conda-forge::jupyterlab
  - conda-forge::ipykernel